name = "Split-Screen Mod"
description = "Adds support for 4-player split-screen to the game"

[preload]
packages = [
    # Skeletons
    "PDLCIN_B3_Anim2",
]
keep_alive = [
    # Skeletons
    "Skeletons.Mesh.Batman_Skeleton_Skin",
]

[options]
layout_horizontal = true # Whether 2P split screen should prefer a horizontal split
letterboxing = true # Whether black bars should appear (true) or the res should be stretched (false)
players = [
    [
        "Playable_RobinStoryDLC",
        "Std",
    ],
    [
        "Playable_Catwoman",
        "Std",
    ],
    [
        "Playable_Nightwing",
        "Std",
    ],
]
